# mode: video

# input: data/test/video/input/
# output: data/test/video/output/

mode: image

input: data/test/images/input/
output: data/test/images/output/

models:
  - model_deeplabV3_plus
  - model_u_net
  - model_u2_net


fps: 50
