hydra:
  output_subdir: null
  run:
    dir: .

defaults:
  - process: process1
  - model: model3
  - _self_

data:
  raw: ${process.raw}
  processed: ${process.processed}
  final: ${process.final}
  results: ${process.results}
  test: data\test\
  validation: data\validation\

augment: True

resolution:
  HEIGHT: 512
  WIDTH: 512